# Makefile for the Himax touchscreen drivers.

# wangbing@wind-mobi.com 20180316 begin
obj-$(CONFIG_TOUCHSCREEN_HIMAX_I2C)		+= himax_platform.o himax_ic.o himax_common.o himax_debug.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_ITO_TEST)	+= himax_ito_test.o
# wangbing@wind-mobi.com 20180316 end
